### ISSUE TITLE
Data Mistake - 02 Aug

### ISSUE THREAD

**Issue by rosenbergd** [JayWelsh/coronamap#1]
There seems to be an issue with the `Active Cases` graph on the 2nd of August, it jumps to 511,485 which was the `Cumulative Cases` value at the time

**Comment by JayWelsh** [comment]
Thanks a lot @rosenbergd , will take a look into this ASAP.

Really appreciate you logging an issue <3

**Comment by JayWelsh** [comment]
@rosenbergd Corrected via: https://github.com/dsfsi/covid19za/pull/629

<img width="1358" alt="Screenshot 2020-08-07 at 16 51 02" src="https://user-images.githubusercontent.com/14224459/89657969-3a3a8e00-d8ce-11ea-9039-815406783dcb.png">

Thanks for the help!
