### ISSUE TITLE
Double data points on 14 October

### ISSUE THREAD

**Issue by rosenbergd** [JayWelsh/coronamap#4]
Hi,

Your personal issue creator here, I just went on again and found 2 data points on the 14th of October (it seems to be happening on all 3 cumulative graphs, recoveries, deaths and tests):
![image](https://user-images.githubusercontent.com/5484305/96495844-b9423000-1248-11eb-8ab0-88836bbfa7a4.png)

**Comment by JayWelsh** [comment]
Hi @rosenbergd 

Thanks again for being such an incredible human being!

I have opened a request to the data source to correct the error here: https://github.com/dsfsi/covid19za/pull/730

I will close this issue once the error has been corrected!

Much appreciated as always, thank you so much! 🌈 🌟 ☮️

**Comment by JayWelsh** [comment]
Fixed in https://github.com/dsfsi/covid19za/pull/732

Thanks <3
